# Generated by Django 6.0.4 on 2026-04-28 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_product_category_product_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='old_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_products', to='api.category'),
        ),
    ]
