# Generated by Django 5.1.2 on 2026-05-27 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_brand_cover_image_brand_is_active_brand_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_eu', models.CharField(max_length=10, verbose_name='Size (EU)')),
                ('size_cm', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Measurement (CM)')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='api.product')),
            ],
            options={
                'verbose_name': 'Product Size',
                'verbose_name_plural': 'Product Sizes',
                'ordering': ['size_eu'],
            },
        ),
    ]
