# Generated by Django 5.1.2 on 2026-06-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_baladiya_name_ar_order_baladiya_order_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, default='EXPLORE NEW RELEASES', max_length=100, null=True),
        ),
    ]
