# Generated by Django 5.1.2 on 2026-06-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_productimage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
