# Generated by Django 5.1.2 on 2026-06-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_banner_button_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_text', models.CharField(default='EXPLORE NEW RELEASES', max_length=100)),
                ('button_link', models.CharField(default='/latest-drops', max_length=255)),
            ],
            options={
                'verbose_name': 'Banner Call to Action',
                'verbose_name_plural': 'Banner Call to Action',
            },
        ),
        migrations.RemoveField(
            model_name='banner',
            name='button_text',
        ),
    ]
